version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - "env_file: ./.env"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgress}
      POSTGRES_DB: ${DB_NAME:-telegram_client}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
